Rails.application.config.assets.precompile << 'ui-bg_highlight-soft_2.png'
Rails.application.config.assets.precompile << 'ui-bg_gloss-wave_2.png'
Rails.application.config.assets.precompile << 'ui-bg_glass_100_f6f6f6_1x400.png'
Rails.application.config.assets.precompile << 'ui-bg_glass_100_fdf5ce_1x400.png'
Rails.application.config.assets.precompile << 'ui-bg_glass_65_ffffff_1x400.png'
Rails.application.config.assets.precompile << 'ui-bg_highlight-soft_1.png'
Rails.application.config.assets.precompile << 'ui-bg_diagonals-thick_1.png'
Rails.application.config.assets.precompile << 'ui-icons_222222_256x240.png'
Rails.application.config.assets.precompile << 'ui-icons_ffffff_256x240.png'
Rails.application.config.assets.precompile << 'ui-icons_ef8c08_256x240.png'
Rails.application.config.assets.precompile << 'ui-icons_ef8c08_256x240.png'
Rails.application.config.assets.precompile << 'ui-icons_ef8c08_256x240.png'
Rails.application.config.assets.precompile << 'ui-icons_228ef1_256x240.png'
Rails.application.config.assets.precompile << 'ui-icons_ffd27a_256x240.png'
Rails.application.config.assets.precompile << 'ui-bg_diagonals-thick_2.png'
Rails.application.config.assets.precompile << 'ui-bg_flat_10_000000_40x100.png'

